### ISSUE TITLE
move to pystac

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/pystac-client#1]
I'm wondering if it makes sense to move this to pystac.  I think it makes sense because there aren't any additional dependencies besides pystac itself.

cc @lossyrob

**Comment by lossyrob** [comment]
Oh - I figured there were or will be additional dependencies, but maybe I'm mistaken. I was thinking at least `requests` would be in the mix.

@matthewhanson thoughts?

**Comment by matthewhanson** [comment]
I think it's still TBD on what the dependencies will be. It may make sense to integrate the two at that time but given that it's going to be undergoing some frequent and rapid development it makes sense to keep it in this repo for now.

We'll be working on this over the next month so I say we leave this issue open see where things stand in April.

**Comment by matthewhanson** [comment]
Consensus is that pystac-client is best as a separate library
