### ISSUE TITLE
tutorials.rst contains broken links

### ISSUE THREAD

**Issue by stark525** [stac-utils/pystac-client#104]
https://github.com/stac-utils/pystac-client/blob/main/docs/tutorials.rst. I'll PR a fix for this tonight.

**Comment by matthewhanson** [comment]
The links won't work in the rst files, but are used to build the readthedocs documentation, where the links are resolving:
https://pystac-client.readthedocs.io/en/latest/tutorials.html

**Comment by stark525** [comment]
Oops, looks good. Thanks!
