### ISSUE TITLE
Url for getting collection list

### ISSUE THREAD

**Issue by john35452** [stac-utils/pystac-client#111]
Hi here,

I found the url to get collection list from catalog in current implementation is appending "/collections" behind url, and it will run into some problem if we have some query parameters.
 
https://github.com/stac-utils/pystac-client/blob/main/pystac_client/client.py#L98
```
url = self.get_self_href() + '/collections'
```

Could we add the "/collections" to url path instead of url itself?
Like the below codes which works for me.
```
from urllib.parse import urlparse, urlunparse
            base = urlparse(self.get_self_href())
            base = base._replace(path=base.path + '/collections')
            url = urlunparse(base)
```

Thanks a lot for the help!

Best regards,
John

**Comment by matthewhanson** [comment]
Hi @john35452 I'd like to understand this use case a bit more.  It sounds like you are providing custom GET parameters to the URL you provide in `Client.open`, is that right?  That could be a problem if you expect those parameters to be used in other calls (such as to /collections/<cid> or /collections/<cid>/items or /collections/<cid>/items/<itemid> or /search) which may not always be GET requests, in fact pystac-client favors POST.

A recent PR added the ability to provide custom parameters when opening up the initial client:

```
client = Client.open(url, parameters={'my_custom_param': <param>})
```

which will pass the parameters along via GET or POST as needed.  Would this server your purpose?
