### ISSUE TITLE
Citing this Package

### ISSUE THREAD

**Issue by matthewpurri** [stac-utils/pystac-client#116]
Hi all,

Thank you for the great work on this package!  I am using your tool to create a dataset for a machine learning paper and I would love to cite this package.  Do you have a prefered way to cite this repository?

**Comment by matthewhanson** [comment]
Hello @matthewpurri , happy to hear you find this useful.  I looked around a bit for best practices on citing GitHub repos and it seems some folks create a DOI that can be cited something like [Zenodo](https://zenodo.org/) or [OSF](https://osf.io/).  I'm not sure what is best and we may consider creating a DOI in the future. 
In the meantime I think the best practice is to link to a specific version of this repo. So if you are using the latest 0.3.0 version, reference https://github.com/stac-utils/pystac-client/tree/v0.3.0
