### ISSUE TITLE
Support for 'timeout' parameter

### ISSUE THREAD

**Issue by Samweli** [stac-utils/pystac-client#127]
Is there a way to pass request timeout value to the Client? Looking at the client couldn't find an API for it.

**Comment by matthewhanson** [comment]
Hello @Samweli, I've not had problems with the client timing out. Can you provide some more information about how you are using pystac-client and whatever error you may be getting?

**Comment by Samweli** [comment]
Hi @matthewhanson, thanks for the response, I'm using the pystac-client in developing QGIS STAC browser(see https://stac-utils.github.io/qgis-stac-plugin/), and timeout is one of the settings we will like to expose to the user.
