### ISSUE TITLE
CLI: Collection Listing Working; Search is returning CloudFront Error

### ISSUE THREAD

**Issue by jlaura** [stac-utils/pystac-client#133]
```
❯ stac-client --version
0.3.1
```

Executing: `stac-client collections https://jat52qc8c0.execute-api.us-west-2.amazonaws.com/dev/` I see a standard JSON response as expected.

Executing a search, I get the following:

```
❯ stac-client search https://jat52qc8c0.execute-api.us-west-2.amazonaws.com/dev/ --matched
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: xEEDNyz0j2Fslf5cqzyzxgJp0Pqq_9HFb6XvcudmVi9zdLRna0ZmlQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

Using a browser works well. Am I perhaps missing a header or has something changed recently? I redeployed the stac-server service and am seeing this result so I assume it is user/deployer error on stac-server.

**Comment by matthewhanson** [comment]
@jlaura sorry for the unreasonably long delay here.  I've not been able to replicate this issue, but it certainly sounds like a stac-server issue.  I'm closing this for now but please feel free to comment, open a new issue or reach out to me if there's still some problems.

**Comment by jlaura** [comment]
@matthewhanson I was just able to update to 0.4.0. I am seeing the same behavior. To replicate: `stac-client search https://stac.astrogeology.usgs.gov/api --matched` This returns the previously posted message. 

Collections list without a problem. If I browse to `https://stac.astrogeology.usgs.gov/api/search`, no issues at all. Two thoughts:

  1. is pystac or pystac client stripping the (s) off the https request somewhere?
  2. is pystac client does something with the URL and appending a trailing '/'? That seems to be causing issues on the api endpoint.

I also tested cloudfront setting a redirect from http to https and that was not successful.

**Comment by jlaura** [comment]
Edit - @matthewhanson 

This is a cloudfront configuration problem. I was able to resolve this by having cloudfront support PUT/POST over https. Posting here in case other run into this problem.
