### ISSUE TITLE
Use OAFeat items endpoint for get_item

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac-client#136]
The `CollectionClient` class relies on the inherited [`Collection.get_item`](https://github.com/stac-utils/pystac/blob/4b302179a7c32c97b983fd90308534a6d15708d9/pystac/catalog.py#L401-L420) method to fetch an Item by ID. This results in looping over all the Items in the Collection until the one with the correct ID is found, which can be extremely inefficient for large collections. For example, using `CollectionClient.get_item` to fetch the `ref_landcovernet_v1_source_35KNT_04_20180105` Item from the the `ref_landcovernet_v1_source` Collection in Radiant MLHub is still running after 10 minutes for me.

The OGC API - Features spec provides a `/collections/{collection_id}/items/{item_id}` endpoint that can be used to fetch an Item directly by ID. Making a request for the example Item above using this endpoint resolves in under a second.

It seems worthwhile for `CollectionClient` to override the inherited `get_item` method to use this endpoint if the [proper conformance classes](https://github.com/radiantearth/stac-api-spec/tree/master/ogcapi-features) are present and fall back to using the inherited method if they are not.

**Comment by duckontheweb** [comment]
cc: @KennSmithDS

**Comment by matthewhanson** [comment]
Thanks @duckontheweb , we will add a `CollectionClient.get_item` function in the next release.
