### ISSUE TITLE
Issues with pip install pystac-client for Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [stac-utils/pystac-client#137]
Hi all,

I am trying to import pystac-client to use as part of this planetary computer demo here.

https://github.com/microsoft/PlanetaryComputerExamples/blob/main/datasets/sentinel-2-l2a/sentinel-2-l2a-example.ipynb

Interesting behavior. On Windows 10 with pip 10.0.1 pystac-client downloads correctly. But on a Ubuntu 18.04.4 Jupyter server I get an error telling me that there is not a proper pystac-client distro available. I have tried for just about every version in the list:

WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pystac-client
  Downloading pystac_client-0.3.0-py3-none-any.whl (25 kB)
ERROR: Could not find a version that satisfies the requirement pystac~=1.1.0 (from pystac-client) (from versions: 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.5.0rc1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0rc1, 1.0.0rc2)
ERROR: No matching distribution found for pystac~=1.1.0 (from pystac-client)
WARNING: You are using pip version 20.2.2; however, version 21.3.1 is available.
You should consider upgrading via the '/env/bin/python3 -m pip install --upgrade pip' command.

I was able to easily pip install planetary_computer on the server and that worked, but having issues with pystac-client today. Does anyone have any experience with this, maybe related to specific pip versions etc?

Thanks for your help!

**Comment by matthewhanson** [comment]
Hello @VallesMarinerisExplorer , sorry there hasn't been a response here. Since pystac has had releases since I'm wondering if this is still a problem or if you had discovered the problem. Thanks in advance!

**Comment by philvarner** [comment]
CNR
