### ISSUE TITLE
NotImplementedError: No link with "rel" type of "search" could be found in this catalog

### ISSUE THREAD

**Issue by cordmaur** [stac-utils/pystac-client#141]
Raising issue here as suggested in https://github.com/stac-utils/pystac/issues/736#issuecomment-1041563811

**Original:**
I have created a local catalog as explained in tutorial https://pystac.readthedocs.io/en/1.0/tutorials/how-to-create-stac-catalogs.html, and I can access the items normally (even stack them with stackstac). However, when I try to search items through pystac-client, I receive the error, saying that I don't have a 'search' link:
NotImplementedError: No link with "rel" type of "search" could be found in this catalog

I couldn't find in pystac documentation how to create such search endpoint for a local catalog. Is it even possible ?

**Reply** posted by @duckontheweb in https://github.com/stac-utils/pystac/issues/736#issuecomment-1041563811_

@cordmaur The `"search"` link is defined in the STAC API Spec and would not be a part of a static catalog since it would require some kind of backend to implement all of the search capabilities. 

I think it would be worth raising this issue in the `pystac-client` repo since `pystac-client` claims to be "A Python client for working with [STAC](https://stacspec.org/) Catalogs and APIs" and should probably be able to handle this gracefully.

**Comment by cordmaur** [comment]
Thanks @duckontheweb, looping through the items and filtering them is exactly what I am doing (even with some spatial filtering), but I wanted something more robust that mimics the STAC API specs locally. It would be easier to port from local to the cloud I think.

**Comment by giswqs** [comment]
I just ran into the same error, which can be reproduced using the script below. 

```python
from pystac_client import Client
url = 'https://esri-lulc-2020-stac.s3.amazonaws.com/catalog.json'
root_catalog = Client.open(url)

area_of_interest = {
    "type": "Polygon",
    "coordinates": [
        [
            [-122.27508544921875, 47.54687159892238],
            [-121.96128845214844, 47.54687159892238],
            [-121.96128845214844, 47.745787772920934],
            [-122.27508544921875, 47.745787772920934],
            [-122.27508544921875, 47.54687159892238],
        ]
    ],
}

root_catalog.search(intersects=area_of_interest)
```

**Comment by giswqs** [comment]
Also the same error with these two catalogs. 

- https://canada-spot-ortho.s3.amazonaws.com/catalog.json
- https://www.planet.com/data/stac/catalog.json

**Comment by cordmaur** [comment]
@giswqs, it seems they published the static catalog. 
The search functionality is provided only on dynamic catalogs that implement the full <b>stac-api</b> specifications.
Short summary from Planet blog (https://developers.planet.com/planetschool/introduction-to-stac-part-1-an-overview-of-the-specification/): 

<i>"
Dynamic versus Static STAC Catalogs[¶](https://developers.planet.com/planetschool/introduction-to-stac-part-1-an-overview-of-the-specification/#Dynamic-versus-Static-STAC-Catalogs)[](https://developers.planet.com/planetschool/introduction-to-stac-part-1-an-overview-of-the-specification/#STAC-API)
STAC Catalogs can be static, by creating the json files and storing them either in local directories, on file servers, or stored on cloud services like Amazon Simple Storage Service (Amazon S3)or Google Cloud Storage.

This makes static STAC Catalogs highly portable, reliable, providing a solid foundation for building dynamic versions through the use of APIs.

STAC API
This leads us to STAC APIs, the last component of the STAC specification. A STAC API is a RESTful API specification for querying STAC catalogs in a dynamic way. It is designed with a standard set of endpoints for searching catalogs, collections, and items.

You can find details in the API specification here: https://github.com/radiantearth/stac-api-spec
"</i>

**Comment by matthewhanson** [comment]
As @duckontheweb said, this is the intended behavior. Static catalogs have no search functionality because the data is not indexed and accessible via the STAC API spec. 
However it would be good for a better error message...perhaps if pystac-client determines this is a static catalog it should return an error saying search is not supported in static catalogs.

I'm adding this to 0.4 to add a better error message.

**Comment by frandorr** [comment]
I'm having this error only with v0.3.3, but it works fine with v0.3.2.
Code sample (taken from [stacstack basic example](https://stackstac.readthedocs.io/en/latest/basic.html)):

```
import pystac_client
URL = "https://earth-search.aws.element84.com/v0"
catalog = pystac_client.Client.open(URL)
lon, lat = -105.78, 35.79
items = catalog.search(
    intersects=dict(type="Point", coordinates=[lon, lat]),
    collections=["sentinel-s2-l2a-cogs"],
    datetime="2020-04-01/2020-05-01"
).get_all_items()
len(items)
```

**Comment by mdmaas** [comment]
I also got this error when porting code from [sat-search](https://github.com/sat-utils/sat-search) (which I guess is deprecated now), and using it to query the earth-search server on AWS `https://earth-search.aws.element84.com/v0`.

I guess that the old client downloaded the static catalog and performed the search locally. If so, my guess is that we should read the entire catalog as a GeoDataFrame and perform a spatial join, am I right? 

In any case, it would be nice if the old functionality were maintained and `api.search` could either run a local search if the STAC server is static, or a query if the server is dynamic, in a way such that if a static server eventually implements the dynamic feature, the client code doesn't need to be changed.

**Comment by aazuspan** [comment]
This issue occurs with catalogs that *do* have `search` links (e.g. https://earth-search.aws.element84.com/v0) if the search link media type is JSON instead of GeoJSON (as is now [specified by pystac-client](https://github.com/stac-utils/pystac-client/blob/c23012022070cd3c33ab4047876690d91cf83586/pystac_client/client.py#L171) as of `0.3.3`).

To demonstrate with `pystac-client==0.3.3` and `pystac==1.4.0`:
```python
from pystac_client import Client
import pystac

catalog = Client.open("https://earth-search.aws.element84.com/v0")

# None
print(catalog.get_single_link("search", media_type=pystac.MediaType.GEOJSON))

# <Link rel=search target=https://earth-search.aws.element84.com/v0/search>
print(catalog.get_single_link("search", media_type=pystac.MediaType.JSON))
```

Is there a reason search endpoints need to return GeoJSON now?

**Comment by mdmaas** [comment]
Thanks @aazuspan for clarifying this issue.

As a quick fix, I'm still using sat-search for that endpoint, and pystac-client for USGS Landsat.

It'd be nice to know when we can switch over to pystac-client for earth-search, because either the server is updated, or the client offers backwards compatibility. 

For what I read online, GeoJSON is a well-specified standard, while JSON is not. So it's probably a better idea to wait for an update on the server side rather than to support non-standard confirming servers.
