### ISSUE TITLE
Improve support for `cql2-text` GET requests

### ISSUE THREAD

**Issue by mmcfarland** [stac-utils/pystac-client#149]
Allow for `filter-lang` value of "cql2-text" and when supplied in conjunction with a string value for the `filter` argument, perform a `GET` request against the search endpoint. 

This currently works:

```python
catalog = Client.open( "https://planetarycomputer-staging.microsoft.com/api/stac/v1")

search = catalog.search(
    method="GET",
    filter_lang="cql2-text",
    filter="collection = 'sentinel-2-l2a' and eo:cloud_cover < 5 and sat:relative_orbit > 58"
)
```

However, if one doesn't supply the `method`, the server responds with a misleading error that is related it receiving a `POST` request. If `filter_lang` isn't supplied, `filter` is ignored. As a convenience, perhaps when `filter` is set to a string, both `filter_lang` and `method` are set internally.

**Comment by matthewhanson** [comment]
So it sounds like if `cql2-text` is provided by the user, pystac-client should make a GET request if `method` is not provided.

Which makes sense, however if the user does specify `POST` with `cql2-text` this should also work and if the server is responding with an error then it may not be correctly handling `cql2-text` with POST.

**Comment by philvarner** [comment]
The spec allows either cql2-text or cql2-json in either GET or POST, but doesn't require both be supported. The recommendation is to at least support cql2-text for GET and cql2-json for POST. There's no way in the conformance classes to distinguish which combo you support, which isn't a problem in OAFeat b/c that only supports GET, but is in STAC API b/c of it's POST support. 

```python
search = catalog.search(
    filter="collection = 'sentinel-2-l2a' and eo:cloud_cover < 5 and sat:relative_orbit > 58"
)
```

e.g., filter is a string, equates to:

```python
search = catalog.search(
    method="GET",
    filter_lang="cql2-text",
    filter="collection = 'sentinel-2-l2a' and eo:cloud_cover < 5 and sat:relative_orbit > 58"
)
```

```python
search = catalog.search(
    filter={ cql2-json dict } 
)
```

e.g., filter is a dict, equates to:


```python
search = catalog.search(
    method="POST",
    filter_lang="cql2-json",
    filter={ cql2-json dict } 
)
```

So the decision tree for determining values if not specified should be:
1. string -> filter_lang = cql2-text
2. dict -> filter_lang = cql2-json
3. cql2-json -> POST
4. cql2-text -> GET

So, if you really wanted to do this, you could, but you have to explicitly specify each field:

```python
search = catalog.search(
    method="GET",
    filter_lang="cql2-json",
    filter="a cql2 json string"
)
```
