### ISSUE TITLE
Add free-text search extension

### ISSUE THREAD

**Issue by Mahir-Sparkess** [stac-utils/pystac-client#157]
Hello,

I would like to suggest the addition of the [free-text-extension](https://api.stacspec.org/v1.0.0-beta.2/item-search#free-text-search) to the PySTAC Client. It's a search extension that allows the feature to search a string, complete or partial string across the properties. I think it's a nice search feature that's very simple without any required formatting of the request.

I have a PR that adds the free-text-search extension with the 'q' parameter added to Item Search.

Thanks.

**Comment by gadomski** [comment]
See https://github.com/stac-utils/pystac-client/pull/158#issuecomment-1309429370 for rationale.
