### ISSUE TITLE
Deploy to ReadTheDocs

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac-client#16]
The [ReadTheDocs page](https://pystac-api.readthedocs.io/en/latest/) still wants to build from the old repo (`duckontheweb/pystac-api`). I'll update that project so that it builds from this location instead.

**Comment by duckontheweb** [comment]
@matthewhanson I deleted the old ReadTheDocs project that was building docs from `duckontheweb/pystac-api`. I figure you're probably setting up docs as part of your CI work, but let me know if you need me to do anything else on this front.

**Comment by matthewhanson** [comment]
I don't see CI for building docs in PySTAC...is it using ReadTheDocs?

**Comment by duckontheweb** [comment]
Yeah, it uses ReadTheDocs. Maybe we can add this as a project under the same account.

**Comment by duckontheweb** [comment]
@lossyrob Is there a ReadTheDocs account associated with the stac-utils org that we should use for this? Possible the one that PySTAC's docs are under?

**Comment by lossyrob** [comment]
Yes, there is - I just figured out how to log into it. It uses the github account of `stacutils`. I'll see if I can quickly add this project, otherwise if there's already docs can you add `stacutils` as an owner as well?

**Comment by lossyrob** [comment]
Ok, I set it up here, with github hooks I think working - https://readthedocs.org/projects/pystac-client/.

@duckontheweb made you a maintainer. @matthewhanson is your readthedocs handle the same as your github? I'll make you a maintainer as well

**Comment by duckontheweb** [comment]
Thanks. Looks like the build is failing, but I can fix that in a PR.
