### ISSUE TITLE
Virtual environment + build tools

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac-client#20]
Using [`poetry`](https://python-poetry.org/) is nice for a lot of reasons, but might end up being a barrier to some contributors if it's not part of their workflow already. Bringing the build and environment tools for this library in line with what PySTAC uses might encourage more contribution.

**Comment by matthewhanson** [comment]
The main branch has been updated to use setuptools, although the docs and other file remnants needs to be cleaned up.
