### ISSUE TITLE
Support context fragment in `ItemSearch.matched`

### ISSUE THREAD

**Issue by hamzaelsaawy** [stac-utils/pystac-client#22]
Currently, [`ItemSearch.matched`](https://github.com/stac-utils/pystac-api-client/blob/bc609956cc8f25b7c9ca0151e32ec38a86feb394/pystac_api/item_search.py#L238) requires the `numberMatched` field, but does not understand the [STAC context fragment](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/context#stac-api---context-fragment).

Can the client be updated to accept either field?

**Comment by matthewhanson** [comment]
Hi @hamzaelsaawy this has been updated so that it will check context.matched if it exists, otherwise falls back to numberMatched
