### ISSUE TITLE
Add support for fetching catalog queryables

### ISSUE THREAD

**Issue by Samweli** [stac-utils/pystac-client#231]
Implement API for getting queryables properties as defined in https://github.com/radiantearth/stac-api-spec/blob/master/fragments/filter/README.md#queryables, for the STAC catalogs that support  additional data driven queriables.

**Comment by jsignell** [comment]
I'm a little torn on what the return type should be for this. I think the user is mostly interested in:

1) What are the fields in properties?
2) What are valid values for those fields?

The response type from the API is a jsonschema. 

I guess in an ideal world there would be a new class that has at least the method: `validate` that can be used to validate any `filter` that is passed to `ItemSearch`.
 
But as a first implementation maybe a `Dict[str, Any]` is ok?
