### ISSUE TITLE
Invalid Search.matched requests should raise an exception?

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac-client#27]
Currently, if I provide an invalid parameter to `.search` and call `.matched()`, a warning is printed.

```python
>>> api = pystac_client.API.open("https://planetarycomputer-staging.microsoft.com/api/stac/v1/")

>>> search = api.search(
...     collections=["sentinel-2-l2a"],
...     bbox=[-93.112301, 29.649001, -92.075965, 30.719868],
...     datetime="2019-07-01/2020-06-30",
... )

>>> search.matched()
numberMatched or context.matched not in response  # this is the warning.
```

If I make that request explicitly, we'll see that the server returned a 422

```python
import requests

payload = dict(
    collection=["sentinel-2-l2a"],
    bbox=[-93.112301, 29.649001, -92.075965, 30.719868],
    datetime="2019-07-01/2020-06-30",
)
>>> r = requests.post("https://planetarycomputer-staging.microsoft.com/api/stac/v1/search", json=payload)
>>> r.status_code
422
```

With this body

```
{'detail': [{'loc': ['body', 'datetime'],
   'msg': 'Invalid datetime, must match format (%Y-%m-%dT%H:%M:%SZ).',
   'type': 'value_error'}]}
```

That information should be surfaced to the user, ideally in an exception.

(as a tangent, I can't tell from the spec if `2019-07-01/2020-06-30` is a valid datetime value or if it has to be `2019-07-01T00:00:00Z/2020-06-30T00:00:00Z`

**Comment by matthewhanson** [comment]
Ah good call - in this case it's not even getting the response. I'll add in error handling on any query so that if you call .search() and it's not a 200 response then an Exception will be thrown
