### ISSUE TITLE
Remove Python 3.7 support

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#272]
PySTAC [dropped Python 3.7 support in v1.6.0](https://github.com/stac-utils/pystac/releases/tag/v1.6.0). IMO **pystac-client** should follow suit, probably in the same way (i.e. making a minor release). Right now, this would be a v0.4.1 release. Thoughts? cc @matthewhanson and @philvarner.

This would unblock #207.

**Comment by philvarner** [comment]
I think this should still be a minor release rather than a patch release.

**Comment by gadomski** [comment]
We're pre-v1.0 so minor releases only increment the last number, right?
