### ISSUE TITLE
CLI behavior

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac-client#31]
Looking for feedback on the behavior of the CLI. 

Right now the default is to hit the API with limit=0 and print the total number matched. To actually fetch the items you specify either `--stdout` or `--save`.  This allows piping of the output to something else such as jq or stacterm.

The requirement of --stdout to print out the results doesn't seem consistent with how most CLIs work. 

Having the default be total matches only is nice to prevent people from making requests on a lot of items.  But maybe it's better to have --matched be the keyword and prevent mistakes in another way (e.g., confirmation, default max_items).

Also --save is redundant since you can just pipe to a file.  Is it worth keeping, or just update docs to show piping to an output file?

So the question is Do we by default fetch items (and have a --matched switch) or a default of matches (and have a --fetch switch)?

**Comment by gadomski** [comment]
> The requirement of --stdout to print out the results doesn't seem consistent with how most CLIs work.

Would it be too complex to split it up, e.g.:
- `stac-client search` does all the things you can do with a single API call, like it does now w/o `--stdout/--save`
- `stac-client fetch` actually grabs items

You could put gates on `fetch` to protect against over-grabbing as well, but at least you know that every `stac-client search` call would be sorta cheap?

> Also --save is redundant since you can just pipe to a file. Is it worth keeping, or just update docs to show piping to an output file?

I personally like having both a direct `--save` option and a pipe option (ala curl etc) -- I think in some build pipelines piping can be a PITA relative to just adding two arguments to a list.
