### ISSUE TITLE
API or Client

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac-client#32]
Since we're keeping inheritance (#19), the API class is interchangeable with a static catalog or an API. The main difference is really that this repo is almost exclusively used for read-only (transaction extension excepted).

Users can use API.open() on any valid endpoint, even a local file.

Should the API class be renamed to Client? STACClient? Something else?

**Comment by gadomski** [comment]
I'd vote for mirroring the repo name change and switch to `Client`.

**Comment by lossyrob** [comment]
+1 `Client`
