### ISSUE TITLE
How can I obtain satellite images as numpy arrays?

### ISSUE THREAD

**Issue by dempsey-ryan** [stac-utils/pystac-client#406]
The tutorial ends sort of abruptly, so I'm not sure what to even do with the item objects that get returned.

My goal is to obtain a satellite image of brightnesses, given a polygon. I followed the intersects tutorial, but I'm not sure what to do with the search.items() to obtain image pixels. Also, what coordinate system is to be used? EPSG 4326? I couldn't find this specified anywhere.

Is this the right package for this task?

**Comment by gadomski** [comment]
Thanks for the question! **pystac-client** only fetches the STAC metadata -- you need another package to actually load in the image data themselves. Two common packages for this are:
- stackstac: https://stackstac.readthedocs.io
- odc-stac: https://odc-stac.readthedocs.io

Both have several tutorials and examples that should help you get started.

**Comment by dempsey-ryan** [comment]
Thanks! What coordinate system should I use when specifying bounding box or intersects parameters? I didn't see that specified

**Comment by gadomski** [comment]
WGS84 geodetic (aka EPSG:4326).
