### ISSUE TITLE
Contributing docs are out of date

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#442]
E.g. they mention `unittest`: https://github.com/stac-utils/pystac-client/blob/2a2f9dcac4e69935777f1b93fa2a5a7151a9c057/docs/contributing.rst. Initially reported by @ircwaves.

**Comment by jsignell** [comment]
There is also substantial overlap with the #Development section of the README. I would recommend updating contributing docs and linking to those rather than repeating the content in the README

**Comment by jsignell** [comment]
Happy to pick this up if people agree

**Comment by gadomski** [comment]
> Happy to pick this up if people agree

Yup, worksforme.
