### ISSUE TITLE
Use STAC_URL environment variable in Client.open

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac-client#47]
Currently, only the command line can use the `STAC_URL` environment variable for automatically discovering the STAC endpoint. It'd be nice to use it with the Python `Client` class as well.

This should do the trick, however I don't have a good idea how to test it. Anyone have thoughts?

```diff
diff --git a/pystac_client/client.py b/pystac_client/client.py
index 0fc03c6..c8e684b 100644
--- a/pystac_client/client.py
+++ b/pystac_client/client.py
@@ -75,13 +75,13 @@ class Client(pystac.Catalog, STACAPIObjectMixin):
         return '<Catalog id={}>'.format(self.id)
 
     @classmethod
-    def open(cls, url, headers=None):
+    def open(cls, url=None, headers=None):
         """Alias for PySTAC's STAC Object `from_file` method
 
         Parameters
         ----------
-        url : str
-            The URL of a STAC Catalog
+        url : str, optional
+            The URL of a STAC Catalog. If not specified, this will use the `STAC_URL` environment variable.
 
         Returns
         -------
@@ -89,6 +89,12 @@ class Client(pystac.Catalog, STACAPIObjectMixin):
         """
         import pystac_client.stac_io
 
+        if url is None:
+            url = os.environ.get("STAC_URL")
+
+        if url is None:
+            raise TypeError("'url' must be specified or the 'STAC_URL' environment variable must be set.")
+
         def read_text_method(url):
             request = Request(url, headers=headers or {})
             return pystac_client.stac_io.read_text_method(request)
```

**Comment by gadomski** [comment]
Got a first try here: https://github.com/stac-utils/pystac-client/compare/main...gadomski:feature/47-stac-url-environ?expand=1. Look like what you were thinking?

**Comment by TomAugspurger** [comment]
Yep, that looks good!

Do you have experience with vcr? My only use of it is through gcsfs, where it was quite painful since it would cause unrelated failures. I'm guessing that things will be smoother here since it's only being used for one test.

**Comment by gadomski** [comment]
It's used other places in the repo, and it can be a little fiddly when you're updating tests, but it's not too bad to do a `pytest --record-mode=new_episodes` when adding a new test like this one.
