### ISSUE TITLE
Can pystac-client be used with an OGC Features API?

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#470]
This question was raised during a meeting recently, and I'm curious. Steps:

- [x] Identify one or more OGC Features APIs to test against
- [ ] Get a collection
- [ ] Get items
- [ ] Filter items with bbox, datetime, and limit
- [ ] Get a single item

**Comment by jsignell** [comment]
I did a naive test of this on https://firenrt.delta-backend.com and it didn't just work, but that's as far as I got. Feel free to use that url to test against.

Example notebook using owslib: https://nasa-impact.github.io/veda-docs/example-notebooks/wfs.html

**Comment by gadomski** [comment]
Yup, agreed that it doesn't work because the landing page doesn't have a `type` field:

```text
ClientTypeError: Could not open Client (href=https://firenrt.delta-backend.com/), expected type=Catalog, found type=None
```

Closing, with the answer NO.
