### ISSUE TITLE
Run tutorial notebooks in CI

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#488]
We should use CI to execute our notebooks (w/ `jupyter execute`) to ensure that they don't bitrot.

**Comment by jsignell** [comment]
To be fair, the docs are rendered versions of the notebooks, so maybe we just need some logging when they fail? https://pystac-client.readthedocs.io/en/stable/tutorials/item-search-intersects.html#Item-Search-with-AOI-as-a-pygeoif-Object

**Comment by gadomski** [comment]
> we just need some logging when they fail? 

Yeah, or just fail the doc build so we catch it early.

**Comment by jsignell** [comment]
I guess then the question becomes if a build fails on readthedocs does anyone hear it?

**Comment by gadomski** [comment]
> I guess then the question becomes if a build fails on readthedocs does anyone hear it?

We have a docs check in our CI now (https://github.com/stac-utils/pystac-client/blob/3c830a4c2dd872361c5363512884f261bcd42670/.github/workflows/continuous-integration.yml#L80-L97) so all we need to do is make sure `scripts/build-docs` errors if the notebooks error.

I do want to look into whether we can enable the readthedocs hooks for this repo too.
