### ISSUE TITLE
Documentation on how to use with NASA CMR STAC endpoint

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/pystac-client#50]
I'm trying to migrate over to using pystac-client from https://github.com/sat-utils/sat-search. Specifically, I'd like to use NASA's CMR stac endpoint but I'm unable to get any searches to work using a `bbox` parameter, which is pretty critical! Is this a bug? Or am I missing something important with formatting these keyword arguments? 

For example, the following search does work with sat-search
```python
from satsearch import Search
results = Search(url='https://cmr.earthdata.nasa.gov/stac/LPCLOUD',
                 collections=['HLSS30.v1.5'], 
                 #bbox = [-122.4,41.3,-122.1,41.5], #SatSearchError: "Request failed with status code 400"
                 bbox = '-122.4,41.3,-122.1,41.5', #works! 
                 datetime='2021-01-01/2021-02-01',  
                 #sortby='-properties.datetime' # results in 0 found but no error raised
                )
results.found()
```

But trying to replicate this does not work with pystac-client. 
```python
# Works if bbox commented out
catalog = Client.open("https://cmr.earthdata.nasa.gov/stac/LPCLOUD")
results = catalog.search(collections=['HLSS30.v1.5'],
                         #bbox = [-122.4,41.3,-122.1,41.5], 
                         bbox = '-122.4,41.3,-122.1,41.5',
                         datetime='2021-01-01/2021-02-01',
                         )
print(f"{results.matched()} items found")
```

```pytb
---------------------------------------------------------------------------
APIError                                  Traceback (most recent call last)
<ipython-input-124-b65c76d02221> in <module>
      6                          datetime='2021-01-01/2021-02-01',
      7                          )
----> 8 print(f"{results.matched()} items found")

~/miniconda3/envs/hyp3/lib/python3.9/site-packages/pystac_client/item_search.py in matched(self)
    351 
    352     def matched(self) -> int:
--> 353         resp = make_request(self.session, self.request, {"limit": 0})
    354         found = None
    355         if 'context' in resp:

~/miniconda3/envs/hyp3/lib/python3.9/site-packages/pystac_client/stac_io.py in make_request(session, request, additional_parameters)
     46     resp = session.send(prepped)
     47     if resp.status_code != 200:
---> 48         raise APIError(resp.text)
     49     return resp.json()
     50 

APIError: "Request failed with status code 400"
```

I suspect because of formatting, but the docs do state, bbox can be passed as a string: 
https://github.com/stac-utils/pystac-client/blob/77d95a25a4b6f48e4e0b7a15b210710f463aef96/pystac_client/item_search.py#L111

related: https://github.com/nasa/cmr-stac/issues/153, https://github.com/sat-utils/sat-search/issues/106

**Comment by matthewhanson** [comment]
@scottyhq This is a known issue with CMR-STAC, and unfortunately is a bigger issue that's dragged on. The bbox is expected to be an a string, incorrectly, by CMR-STAC, but pystac-client submits as an array.
A fix is going in this week that will accept array, but it will be a bit before it gets to production.

An easy workaround from the client side is to use the `intersects` search parameter with a Polygon geometry instead of using the bounding box.

**Comment by matthewhanson** [comment]
This issue has been fixed on prod, bbox can be passed as a comma-delimited string (in GET or POST) or an array (POST)
