### ISSUE TITLE
Allow aggregation of queryables across collections

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#505]
It can be useful to find the set of queryables available across collections. Here's one possible usage:

```python
client = Client.open("https://pystac-client.test")

# GET /queryables
_: Set[str] = client.queryables()

# GET /queryables/collection-a/queryables
# GET /queryables/collection-b/queryables
# Put all queryables in a set and return
_: Set[str] = client.queryables(["collection-a", "collection-b"])
```

There's a question to resolve around whether `queryables()` should hit `/queryables` or do an aggregation of _all_ collections.

**Comment by jsignell** [comment]
Is the response different from `get_queryables`? If we want allow aggregation maybe we could add a `recursive` option to `get_queryables`?

**Comment by gadomski** [comment]
Ah no, thanks! I forgot that we just added that :-). The primary motivating use-case was around "I have this subset of collections that I want to query against", so just `recursive` wouldn't be enough -- we'll want to specify collection ids. But maybe:

```python
client.get_queryables(collections=["a", "b"])
```

that would hit `/collections/a/queryables` and `/collections/b/queryables` and union the queryables together.

**Comment by jsignell** [comment]
Yeah and that feels more ergonomic than something like this?

```python
set(client.get_collection(c).get_queryables() for c in ["a", "b"])
```
