### ISSUE TITLE
urllib3 release breaks tests

### ISSUE THREAD

**Issue by jsignell** [stac-utils/pystac-client#509]
It looks like urllib3 2.0.2 was released yesterday and it seems to be causing the tests to fail: #508 

It might be related to https://github.com/psf/requests/issues/6432 or something else

**Comment by gadomski** [comment]
I think it's just this? https://github.com/kevin1024/vcrpy/issues/688#issuecomment-1533416925

Latest requests supports urllib3: https://github.com/psf/requests/releases/tag/v2.30.0

**Comment by jsignell** [comment]
Nice sleuthing. So we just wait with faiing tests or should we pin around it temporarily with the understanding that we will not release with a ceiling?

**Comment by gadomski** [comment]
LOL I was in the process of writing https://github.com/stac-utils/pystac-client/pull/480#issuecomment-1534967556, let's ceil and move along.

**Comment by jsignell** [comment]
Leaving this open to track reverting https://github.com/stac-utils/pystac-client/pull/508 before release.
