### ISSUE TITLE
Enable ruff's `I` rules

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#515]
Import sorting isn't enabled by default, but we should turn it on. See https://github.com/stac-utils/stactools/pull/424/commits/3e1ee88f6859c143d8f07413fc2436c1621172d6 for an example of adding it to `pyproject.toml` and `.pre-commit-config.yaml`.

**Comment by jsignell** [comment]
I am a big fan of import sorting and absolutifying (although I'm not sure if ruff has that).

**Comment by gadomski** [comment]
> I am a big fan of import sorting and absolutifying (although I'm not sure if ruff has that).

Sorting yes, absolutifying there's at least a lint for that: https://beta.ruff.rs/docs/rules/relative-imports/. I tend towards not-minding `from .sibling import Klass` but I'm +/-0 on the ruleset -- this is in the category of "I don't mind either way as long as we pick one."

**Comment by ircwaves** [comment]
It's all relative.  Absolute imports _are_ relative to the python path of the current execution.  Relative imports are relative to the location in the directory structure from the current module.  Not that I've ever had the same package installed in two different spots in my `PYTHONPATH`.

**Comment by jsignell** [comment]
> I'm +/-0 on the ruleset -- this is in the category of "I don't mind either way as long as we pick one."

Yeah same same, absolute just seems to be the direction people go when they want to enforce picking :shrug:
