### ISSUE TITLE
v0.7 missing typing_extensions module

### ISSUE THREAD

**Issue by giswqs** [stac-utils/pystac-client#540]
It seems v0.7 is broken. 

https://github.com/giswqs/Planetary-Computer-Catalog/actions/runs/5250953023/jobs/9485412494

```text
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 29, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'
```
![image](https://github.com/stac-utils/pystac-client/assets/5016453/e4807ba9-c9a2-4d8c-aee0-99e69767c54b)

**Comment by gadomski** [comment]
@giswqs thanks for the report! We'll release v0.7.1 shortly with the fix.
