### ISSUE TITLE
Is pystac-client a replacement for sat-search

### ISSUE THREAD

**Issue by bidhya** [stac-utils/pystac-client#55]
I have been using sat-search (https://github.com/sat-utils/sat-search) to query and download data. Is pystac-client a newer api that will replace sat-search?
Is sat-search going to be deprecated anytime soon?

**Comment by matthewhanson** [comment]
Hello @bidhya , sorry I totally missed this ticket when you posted it.

Yes, pystac-client is a replacement for sat-search, and sat-search will most likely be deprecated in the near future.
There are two things that can't be done with pystac-client that you can do with sat-search:

- you can't automatically download assets, PySTAC nor pystac-client have functions for downloading assets as local files. I expect there to be another library to handle downloading of STAC assets locally that will handle multiple protocols (e.g., http, s3, etc)
- pystac-client has a CLI, but it does not have the calendar output feature that sat-search does. However, you can use stac-terminal alongside pystac-client to do that and more: https://github.com/stac-utils/stac-terminal

**Comment by bidhya** [comment]
Thank you, Matthew. Search/subset and finally downloading of assets has been the most important feature of sat-search for me. I will wait until the download feature is available to pystac-client or one of its never derivate.
