### ISSUE TITLE
Crash on likely non-compliant server

### ISSUE THREAD

**Issue by lnicola** [stac-utils/pystac-client#553]
I noticed that `stac-client collections https://datahub.creodias.eu/stac/` crashes in a pretty obscure way (a NoneError, more or less).

The server is probably not exactly compliant, but it would be nice to report a more useful error.

**Comment by jsignell** [comment]
I just transferred this issue to the pystac-client repo (which provides the `stac-client` CLI) since it's this library that is not raising an informative enough error.
