### ISSUE TITLE
Replace print statements with appropriate logging

### ISSUE THREAD

**Issue by Geosynopsis** [stac-utils/pystac-client#566]
Thanks for the great work you all. In light of the recent [PR](https://github.com/stac-utils/pystac-client/pull/554), it came to notice that we are using print statements in the library instead of proper logging. As this is a library used by other applications, adding logging can allow the user to filter messages with different severity on their end and collect messages in the appropriate place. It's the user's choice to dump the traceback on standard output / error or not, which can be a security issue in certain environments.

**Comment by jsignell** [comment]
Yeah good point. I think I noticed that when writing that PR but clearly I didn't take the time to systematically go through and fix.

**Comment by jsignell** [comment]
I am just looking at this again and want to confirm that `print` is appropriate for dumping output to the user. I don't think logging should be used for that.
