### ISSUE TITLE
Only subset of items returned

### ISSUE THREAD

**Issue by idantene** [stac-utils/pystac-client#583]
Hey!

Allow me to start by stating I'm not sure if this is a pystac-client issue or an earth search issue.
We've been using v0 for earth search for a while and it's all been great. I'm not sure if this was a recent change to some API, but I noticed that suddenly we're not getting all of the available items within our query parameters.

For example, running:
```python3
stac_client = pystac_client.Client.open("https://earth-search.aws.element84.com/v0")
stac_client.add_conforms_to("ITEM_SEARCH")
query = stac_client.search(collections=["sentinel-s2-l2a-cogs"],
                           bbox=wgs_bounds, datetime=['2023-04-01', '2023-06-15'], limit=None)
```
We're only getting results from April, but none from May or June.
I'm trying to debug this before we migrate to v1, and I was wondering if this is a known issue due to some API changes or out-of-date STAC catalog?

Thanks!

**Comment by gadomski** [comment]
Forward processing has been turned off for the `v0` endpoint, announcement here: https://element84.com/geospatial/introducing-earth-search-v1-new-datasets-now-available/. From that post:

> The [old version (“v0”) of Earth Search](https://earth-search.aws.element84.com/v0) is now considered deprecated and will soon stop receiving updated STAC Items before it is deleted entirely.

When I last checked (https://github.com/cirrus-geo/cirrus-earth-search/issues/37#issuecomment-1692064707), the most recent l2a item was from 06 May 2023.

To stay up-to-date on plans for the v1 endpoint, subscribe to our mailing list -- instructions here: https://github.com/Element84/earth-search/discussions/13. And if you have Earth Search specific issues, we use https://github.com/Element84/earth-search/issues to track those.

HTH!

**Comment by idantene** [comment]
Thanks for the information @gadomski, that certainly helps!
