### ISSUE TITLE
Error message should probably be an f-string

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac-client#64]
https://github.com/stac-utils/pystac-client/blob/2aa5ecf1923d85f7784683c78498cb979ac90288/pystac_client/client.py#L70

The error message looks like:

```
Error https://api.radiant.earth/mlhub/v1/: <class 'pystac_client.exceptions.ConformanceError'> API does not conform to {ConformanceClasses.STAC_API_CORE}. Must contain one of the following URIs to conform (preferably the first):
        https://api.stacspec.org/v1.0.0-beta.1/core
        http://stacspec.org/spec/api/1.0.0-beta.1/core.
```

I'm guessing this is supposed to be an f-string, but isn't.

**Comment by philvarner** [comment]
Also, I triggered this message when connecting a client to `https://api.radiant.earth/mlhub/v1/ `

**Comment by duckontheweb** [comment]
> https://api.radiant.earth/mlhub/v1/

Yeah, our API is not up to date with the latest conformance classes yet.
