### ISSUE TITLE
search result depends on datetime format

### ISSUE THREAD

**Issue by johntruckenbrodt** [stac-utils/pystac-client#644]
Hi. I just observed some unexpected behavior when comparing the search result from queries with `datetime` as string and as `datetime.datetime` object. Can you help me out here?  

The first query returns 20 scenes in the defined time interval. The second query only returns 7 scenes outside the interval.
```python
from datetime import datetime
from pystac_client import Client


def get_href(item):
    assets = item.assets
    ref = assets[list(assets.keys())[0]]
    return ref.href


################################################################
url = 'https://planetarycomputer.microsoft.com/api/stac/v1'
collections = ['sentinel-1-grd']

acq_start = '2022-02-02T12:00:00'
acq_end = '2022-02-02T12:30:00'

pattern = '%Y-%m-%dT%H:%M:%S'
acq_start_dt = datetime.strptime(acq_start, pattern)
acq_end_dt = datetime.strptime(acq_end, pattern)

catalog = Client.open(url)
################################################################
# query 1: datetime as str
result = catalog.search(collections=collections, max_items=None,
                        datetime=[acq_start, acq_end])
result = list(result.items())
print(f'got {len(result)} scenes')
scenes = [get_href(x) for x in result]
print('\n'.join(scenes))
################################################################
# query 2: datetime as datetime.datetime
result = catalog.search(collections=collections, max_items=None,
                        datetime=[acq_start_dt, acq_end_dt])
result = list(result.items())
print(f'got {len(result)} scenes')
scenes = [get_href(x) for x in result]
print('\n'.join(scenes))
```

**Comment by TomAugspurger** [comment]
I'm not sure if it's the cause of the observed difference, but pystac-client will "pad" the end datetime when you pass a string. See the `datetime` parameter at https://pystac-client.readthedocs.io/en/stable/api.html#item-search.

I wonder what you get if you set `pattern = "Y-%m-%dT%H:%M:%S.%f"` or `"Y-%m-%dT%H:%M:%S.999"`

**Comment by johntruckenbrodt** [comment]
Thanks a lot @TomAugspurger for helping to solve this. I changed the strings and pattern but get the same result.  
In the second case, the time is shifted to one hour earlier as can be seen when calling `ItemSearch.url_with_parameters`:
```
...datetime=2022-02-02T12%3A00%3A00Z%2F2022-02-02T12%3A30%3A00Z...
...datetime=2022-02-02T11%3A00%3A00Z%2F2022-02-02T11%3A30%3A00Z...
```

**Comment by TomAugspurger** [comment]
Ah, I was going to suggest timezones as a potential issue, but I misread
the docs. I thought the docs indicated tz-naive timezones would be
interpreted as UTC (i.e. `dt.replace(tzinfo=datetime.timezone.utc)` in
code) rather than converted from your locale to UTC.

Converting timezone-naive, rather than interpreting them as UTC, is a bit
surprising to me. I'd be open to deprecating the current behavior unless
there's strong precedence elsewhere in the stac-utils ecosystem around how
tz-naive datetimes are treated.

**Comment by gadomski** [comment]
> I'd be open to deprecating the current behavior unless
there's strong precedence elsewhere in the stac-utils ecosystem around how
tz-naive datetimes are treated.

There's not a "usual" behavior as far as I know, so changing **pystac-client** to do the least surprising thing gets a 👍🏼 from me.

**Comment by johntruckenbrodt** [comment]
Ah I see. Wouldn't it then be more intuitive to assume the same time zone for strings and datetime objects if not specified by the user?  
From how I interpret [this](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects), the time zone interpretation for unaware objects is up to the application.  

Currently, the documentation of `ItemSearch` reads:
> Instances of `datetime.datetime` may be either timezone aware or unaware. Timezone aware instances will be converted to a UTC timestamp before being passed to the endpoint. Timezone unaware instances are assumed to represent UTC timestamps.

However, `datetime.strptime(acq_start, pattern)` is creating an unaware object and the object is still converted to UTC.

**Comment by gadomski** [comment]
@johntruckenbrodt right you are — thanks for sticking with it. I agree, #686 should fix -- LMK if that matches your understanding.

**Comment by johntruckenbrodt** [comment]
Great! IMO this fixes it. Thanks a lot.
