### ISSUE TITLE
Support for STAC API 1.0.0-beta.2

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac-client#65]
https://tamn.snapplanet.io/ uses 1.0.0-beta.2 in it's conformance classes, and fails with:

```
Error https://tamn.snapplanet.io/: <class 'pystac_client.exceptions.ConformanceError'> API does not conform to {ConformanceClasses.STAC_API_CORE}. Must contain one of the following URIs to conform (preferably the first):
        https://api.stacspec.org/v1.0.0-beta.1/core
        http://stacspec.org/spec/api/1.0.0-beta.1/core.
```

It would be nice to validate against either beta.1 or beta.2 . I recognize this is complex to implement, but it would be nice to support.

**Comment by matthewhanson** [comment]
Will be releasing a beta version of the next release soonish, which handles multiple versions (and currently includes beta.1 and beta.2)
