### ISSUE TITLE
Enhancement: Support searching static catalogs

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/pystac-client#66]
Based on input from @matthewhanson and @TomAugspurger  over in https://github.com/intake/intake-stac/issues/95#issuecomment-865270958, 

> Currently pystac-client will raise an APIError if there is no rel=search link (but it is intended to be a client for both static catalogs and APIs).

It would indeed be nice if pystac-client had the ability to search static catalogs in addition to API endpoints. There are a couple of use-cases for this:

1. Filtering pystac-client search results further (i.e. a local results.json file with an ItemCollection) without having to issue new requests to an API enpoint. 

2. Searching static STAC catalogs that do not have an API endpoint set up.

It would be great if the "local search" function used the same syntax as an API search. Perhaps adding an optional dependency on geopandas would make this easy to implement?

**Comment by matthewhanson** [comment]
I'm not sure if this makes sense to have in pystac-client, or perhaps it's another lightweight library, but it would be useful to be able to crawl and index a catalog into a SQLite file for this purpose.

**Comment by matthewhanson** [comment]
discussed with @gadomski, we're not sure if this is suitable as a pystac-client feature, if for no other reason than it could add a lot of complexity and dependencies.

The first reasonable thing to do here is to index a static catalog into something like sqlite. Not indexing the data and just iterating and filtering will quickly become impractical, and a sqlite solution will handle small or large catalogs.

After indexing into sqlite or similar, there are two main approaches here for searching static catalogs:
- run local STAC API using sqlite as the backend
- provide a programmatic interface for searching the db directly (no RESTful STAC API)

In any case this seems like it may be better suited to it's own library that crawls a static catalog and indexes it, then provides a library and/or API to search that catalog.
