### ISSUE TITLE
limit of between 1 and 10000 should be enforced by client

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac-client#68]
Per the definition of `limit` in OGC API Features (https://docs.opengeospatial.org/is/17-069r3/17-069r3.html), only values between 1 and 10000 are allowed. These restrictions on this parameter should be enforced by the client.

**Comment by matthewhanson** [comment]
It seems strange that a limit of 0 should not be allowed, as it is helpful to specify limit=0 to just get a total count.

**Comment by philvarner** [comment]
I think we decided that this is the default limit, so as to be the same with OGC API Part 1, but that servers can change it by defining different values in the service description.
