### ISSUE TITLE
Fields extension uses incorrect plural `includes` and `excludes`

### ISSUE THREAD

**Issue by kurtmckee** [stac-utils/pystac-client#689]
While interacting with a STAC API using pystac-client I found that pystac-client is submitting "include" and "exclude" fields with plural keys. This doesn't match the Fields extension documentation, and didn't work against the STAC API I was interacting with:

From [the Fields extension documentation's Overview](https://github.com/stac-api-extensions/fields/tree/v1.0.0?tab=readme-ov-file#overview):

> The `fields` object contains two attributes with string array values, `include` and `exclude`.

**Comment by kurtmckee** [comment]
@gadomski Thank you for the quick review and merge! Do you anticipate that this could be released as an 0.8.1 or 0.9.0 release, or are there additional changes in the pipeline that you'd like to wait for?

**Comment by gadomski** [comment]
Should be ok as a v0.8.1, and I can try to get that out today 👍🏼

**Comment by kurtmckee** [comment]
Hooray! Thank you!

**Comment by gadomski** [comment]
https://github.com/stac-utils/pystac-client/releases/tag/v0.8.1

**Comment by kurtmckee** [comment]
Thank you so much! :heart:
