### ISSUE TITLE
0.8.2 PyPI release failed

### ISSUE THREAD

**Issue by johntruckenbrodt** [stac-utils/pystac-client#707]
Hi, the tar.gz of the latest version was not uploaded to PyPI:
https://github.com/stac-utils/pystac-client/actions/runs/9306199404  
https://pypi.org/project/pystac-client/0.8.2/#files  
Would you mind having a look?

**Comment by gadomski** [comment]
@johntruckenbrodt uploaded the source, thanks for the catch! Please re-open if the fix doesn't look correct.

**Comment by johntruckenbrodt** [comment]
Looks good @gadomski, thanks. The conda-forge PR was not automatically opened so I did it.
