### ISSUE TITLE
RFC: Add support for positional arguments

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac-client#78]
My first instinct when using the client is to do:

```bash
stac-client collections https://planetarycomputer.microsoft.com/api/stac/v1
```

i.e. to try to pass a single positional argument. This doesn't work because I'm supposed to use the `--url` flag. This issue is a Request For Comment on adding support for positional arguments when it makes sense. Both `search` and `collections` could probably take the root Catalog URL as a positional argument, e.g..

**Comment by matthewhanson** [comment]
What if using the envvar STAC_URL so it doesn't have to be specified?  
Or maybe having an envvar isn't really all that helpful anyway (as a user you could still use one on your command line if you wanted.  It would then be explicit that you must always provide a URL

**Comment by gadomski** [comment]
> What if using the envvar STAC_URL so it doesn't have to be specified?

Personally I'm not a huge user of config env vars, mostly because they're not super-portable and I always mess up how to use them with scripts correctly. But that's just me.

If a person's doing a lot of command line work w/ one catalog, they could always alias up, e.g.

```
alias stac-search-pc="stac-client search https://planetarycomputer.microsoft.com/api/stac/v1"
```

**Comment by matthewhanson** [comment]
I think I agree, let the user figure out aliasing however they want.  Going to remove the envvar for this release.
