### ISSUE TITLE
Update readthedocs to publish tagged versions

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac-client#85]
Currently only `latest` is built and published on ReadTheDocs.

Update so that each published version is built and stays

**Comment by klsmith-usgs** [comment]
The examples in the docs could use a few QA passes as well.

https://pystac-client.readthedocs.io/en/latest/usage/stac_api.html#item-search
vs
https://github.com/stac-utils/pystac-client/blob/cae89567be8fc263f14b68d16521d0e5846ceabe/pystac_client/item_search.py#L405

**Comment by matthewhanson** [comment]
@klsmith-usgs docs are getting complete overhaul with upcoming 0.3.0 version

Versions are enabled explicitly for each version through the readthedocs admin page.  `0.2.0` has been turned on, as has `docs` which is active but hidden for development purposes.
