### ISSUE TITLE
Download all assets

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/pystac-client#89]
Once I've found some data using the `search` command, I'd like to download all assets. It would be a nice convenience functionality to add so that people don't need to fiddle around with fs libraries themselves.

**Comment by matthewhanson** [comment]
@gadomski and I discussed today. It seems a reasonable thing to expect PySTAC to support via the same STAC_IO mechanism, allowing other libraries to override to allow downloading using other protocols (e.g., s3). 

By default this could support simple http requests.  Recommend adding this as a PySTAC issue. Clients could then override this to support downloading using e.g., fsspec.

**Comment by gadomski** [comment]
N.B. I've created a separate library for this behavior here: https://github.com/gadomski/stac-asset. Once I release v0.1 of **stac-asset** we can could/should this issue in favor of that library.

Reasons why I thought a separate library was appropriate:
- **stac-asset** is async-first, which is pretty key for downloading a bunch of assets at once
- There's some vendor- and implementation-specific logic required to do multi-provider asset-download support. This logic might require more frequent updates than is appropriate for a "base" library like **pystac-client**.
- **stac-asset**'s CLI is currently built to work well w/ **pystac-client**'s CLI output, e.g.:

```shell
stac-client search http://stac-api.test -c foo --max-items 10 | stac-asset download
```

**Comment by gadomski** [comment]
Ok, we're moved to **stac-utils**, so I'm closing this issue as complete-via-other-repo: https://github.com/stac-utils/stac-asset.
