### ISSUE TITLE
Bug in ItemSearch._format_datetime giving wrong date

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac-client#91]
It looks like `_format_datetime` ignores components like the seconds in the right side of the range.

```python
>>> import pystac_client
>>> pystac_client.ItemSearch(None)._format_datetime("2019-01-01T00:00:00Z/2019-01-01T00:12:00")
'2019-01-01T00:00:00Z/2019-01-01T23:59:59Z'
```

I think the expected result is

```
''2019-01-01T00:00:00Z/2019-01-01T00:12:59Z''
```

**Comment by gadomski** [comment]
I'm not sure I agree with the expected result, I think it should be exactly what was given but with timezone added, e.g.

```
2019-01-01T00:00:00Z/2019-01-01T00:12:00Z
```

The use could be specifying an exact time down to the seconds value, so we can't assume they wanted the end of that minute, correct? I think the syntax to specify "end of the minute" would be the awkward `2019-01-01T00:00:00Z/2019-01-01T00:12`?

**Comment by TomAugspurger** [comment]
Oh, yeah I think you're right.

Just to confirm some expected behavior, the idea is that if a resolution is *not* specified, then those will be filled as their highest value. For example, if you only specify up to minutes, then seconds will be filled as 59

```
>>> assert _format_datetime("2019-01-01T00:00:00Z/2019-01-01T00:12") == "2019-01-01T00:00:00Z/2019-01-01T00:12:59Z"
```

**Comment by gadomski** [comment]
> Just to confirm some expected behavior, the idea is that if a resolution is not specified, then those will be filled as their highest value. For example, if you only specify up to minutes, then seconds will be filled as 59

Two corrections:
1. This is true for the second value (`end`) in the `start/end` string, not the first. The first value is filled with the lowest values for unspecified components.
2. This is only implemented for the date parts of the string, not the time (see #29 for the original request). While it wouldn't be too hard technically, just want to make sure sub-daily support for the "abbreviated" datetime syntax is worth the additional code complexity.

**Comment by TomAugspurger** [comment]
Gotcha, thanks. I *think* that https://pystac-client.readthedocs.io/en/latest/client.html#pystac_client.ItemSearch covers that

> expands to the end of that day/month/year...

and I can't really think of a better way to phrase it, so sounds good to me.
