### ISSUE TITLE
Update ConformanceClasses for STAC API 1.0.0-beta3

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac-client#93]
[STAC API 1.0.0-beta3](https://api.stacspec.org/v1.0.0-beta.3/) is now available, and is being used at https://planetarycomputer-staging.microsoft.com/api/stac/v1/.

I've confirmed that this diff fixes the exception I see when trying to search that endpoint with the pystac-client `main`.

```diff
diff --git a/pystac_client/conformance.py b/pystac_client/conformance.py
index 3e57032..697bd65 100644
--- a/pystac_client/conformance.py
+++ b/pystac_client/conformance.py
@@ -29,7 +29,11 @@ True
 """
 from enum import Enum
 
-STAC_PREFIXES = ['https://api.stacspec.org/v1.0.0-beta.2', 'https://api.stacspec.org/v1.0.0-beta.1']
+STAC_PREFIXES = [
+    'https://api.stacspec.org/v1.0.0-beta.3',
+    'https://api.stacspec.org/v1.0.0-beta.2',
+    'https://api.stacspec.org/v1.0.0-beta.1',
+]
 
 
 class ConformanceClasses(Enum):
```

Are there any tests that should be updated, or is it OK to just change the conformance class enum?

**Comment by lossyrob** [comment]
Is there a way to solve this that future proofs it, i.e. accounts for future releases of STAC API (perhaps in the v1.* line, since it will be using semver)? That may alleviate future headaches.

**Comment by fwfichtner** [comment]
Also the string comparison in [StacApiIo](https://github.com/stac-utils/pystac-client/blob/8aaf6503c8138d46be2368325071058a94071af3/pystac_client/stac_api_io.py#L244) can cause problems: 

```python
uris = CONFORMANCE_URIS.get(conformance_class.name, None)

...

if not any(uri in uris for uri in self._conformance):
    return False
```
E.g. [https://api.stacspec.org/v1.0.0-beta.3/item-search/#fields](https://api.stacspec.org/v1.0.0-beta.3/item-search/#fields) would not be conform, while [https://api.stacspec.org/v1.0.0-beta.3/item-search#fields](https://api.stacspec.org/v1.0.0-beta.3/item-search#fields) would be. 

Maybe a solution with `urlparse` would work better here?

**Comment by TomAugspurger** [comment]
FYI, I just discovered the `ignore_conformance` keyword to `pystac_client.Client.open`, for a temporary workaround.

Agreed that we should do some kind of normalization on the URL before checking the conformance.
