### ISSUE TITLE
I cannot enforce cloud coverage condition for retrieval - am I doing it wrong?

### ISSUE THREAD

**Issue by zabop** [stac-utils/pystac-client#94]
First of all, very nice package, thank you for developing it.

I am having an issue with retrieving images which don't have much cloud coverage on them. I explain the whole issue [here](https://gis.stackexchange.com/questions/410888/how-to-retrieve-sentinel-images-without-significant-cloud-coverage-using-python). I also write it here for completeness.

I work in a Google Colab Python notebook. Importing modules:

```
from pystac_client import Client
import rasterio
import matplotlib.pyplot as plt
```
Set up an example bounding box:

```
lat, lon = 1.2987, 103.6549 # a random point in Singapore
bbox={'lonLower':lon-0.1,'latLower':lat-0.1,'lonHigher':lon+0.1,'latHigher':lat+0.1}
```

Search for Sentinel images:

```
catalog = Client.open("https://earth-search.aws.element84.com/v0")

mysearch = catalog.search(collections=['sentinel-s2-l2a-cogs'],
                          bbox=[bbox['lonLower'],bbox['latLower'],bbox['lonHigher'],bbox['latHigher']],
                          query =  {"eo:cloud_cover":{"lt":1}},
                          datetime='2020-01-01/2020-12-31', 
                          max_items=10)   

resdict = mysearch.get_all_items_as_dict()
```

I believe the line ` query =  {"eo:cloud_cover":{"lt":1}}` should make sure I am only retrieving images with cloud cover less than 1 percent. Select the first image, use the B08 band (just for example), plot:

```
url = resdict['features'][0]['assets']['B08']['href']
src = rasterio.open(url)
plt.imshow(src.read(1), cmap='pink')
```

![image](https://user-images.githubusercontent.com/20886570/132822464-54476c60-cc4c-4274-88ff-97a16ea10c60.png)

Singaporean coastline is clearly recognizable. It seems however, that the cloudy parts of the image is way more than 1 percent.

For the same image, I get the Scene Classification Layer by doing:

```
url = resdict['features'][0]['assets']['SCL']['href']
src = rasterio.open(url)
```
Each pixel is assigned an integer value, based on what the layer is according to Sentinel's team. The key is:

![image](https://user-images.githubusercontent.com/20886570/132822652-7328809b-a662-484c-a5a7-c070f616904c.png)

Let's plot the values on a histogram:

```
plt.hist(src.read(1).flatten())
```
![image](https://user-images.githubusercontent.com/20886570/132822679-8b0d08e4-3220-4d04-83e6-60ac67845556.png)

It is clear that pixels classified as `CLOUD_MEDIUM_PROBABILITY` (Label 8) and `CLOUD_HIGH_PROBABILITY` (Label 9) are way more prominent than 1 percent.

**What am I doing wrong, or how should I retrieve images which adhere to the cloud coverage threshold specified?**

Thanks for reading through!

**Comment by matthewhanson** [comment]
Hello @zabop unfortunately this is a known issue.  The problem lies in that the cloud coverage estimates are missing from the L2A metadata, so the processing instead fetches them from the equivalent L1C data...however this doesn't always work because for some reason the L1C metadata is not available at the time of ingest.

However, there is another parameter that helps determine if it is valid or not:  `sentinel:valid_cloud_cover` is true if cloud cover is valid, but if it's not then cloud cover will be 0 and `sentinel:valid_cloud_cover` will be false.

You can include this in your query search:
```
query =  {"eo:cloud_cover":{"lt":1}, "sentinel:valid_cloud_cover": "eq": true}}
```

Which means you'll get fewer scenes overall. This will be fixed in the upcoming v1 of the API, but there is no specific timeline for that yet.

**Comment by matthewhanson** [comment]
@zabop if you have further issues with the Earth-Search API please open a new issue at https://github.com/cirrus-geo/cirrus-earth-search

**Comment by zabop** [comment]
Hi @matthewhanson, thank you for your reply! Alright, I'll ask there if I have something more.
